name: crash-model
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - altair=2.4.1=py36_0
  - asn1crypto=0.24.0=py36_1003
  - astroid=2.2.5=py36_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=3.1.0=py_0
  - boost-cpp=1.68.0=h11c811c_1000
  - branca=0.3.1=py_0
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hf0e25f4_1
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - codecov=2.0.15=py_1
  - coverage=4.5.3=py36h14c3975_0
  - cryptography=2.6.1=py36h9d9f1b6_0
  - curl=7.64.0=h646f8bb_2
  - cycler=0.10.0=py_1
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - descartes=1.1.0=py_2
  - entrypoints=0.3=py36_1000
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.5=hf484d3e_1002
  - fiona=1.8.6=py36hf242f0b_2
  - folium=0.8.3=py_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=2.4.1=py36hf242f0b_0
  - geocoder=1.38.1=py_0
  - geographiclib=1.49=py_0
  - geojson=2.4.1=py_0
  - geopandas=0.4.1=py_1
  - geopy=1.18.1=py_0
  - geos=3.7.1=hf484d3e_1000
  - geotiff=1.4.3=h1105359_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.56.2=had28632_1001
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - ipdb=0.12=py_0
  - ipykernel=5.1.0=py36h24bf2e0_1002
  - ipython=7.4.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - isort=4.3.16=py36_0
  - jdcal=1.4=py_1
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.10=h1978553_1003
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - krb5=1.16.3=h05b26f9_1001
  - lazy-object-proxy=1.3.1=py36h14c3975_1000
  - libcurl=7.64.0=h541490c_2
  - libdap4=3.19.1=hd48c02d_1000
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgdal=2.4.1=hdb8f723_0
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h328b03d_1009
  - libnetcdf=4.6.2=hbdf4f91_1001
  - libpng=1.6.36=h84994c4_1000
  - libpq=11.2=h4770945_0
  - libsodium=1.0.16=h14c3975_1001
  - libspatialindex=1.9.0=he1b5a44_0
  - libspatialite=4.3.0a=hb5ec416_1026
  - libssh2=1.8.1=h22169c7_0
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxgboost=0.82=he1b5a44_0
  - libxml2=2.9.8=h143f9aa_1005
  - mapclassify=2.0.1=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.0.3=py36_0
  - matplotlib-base=3.0.3=py36h167e16e_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py36h14c3975_1000
  - more-itertools=4.3.0=py36_1000
  - munch=2.3.2=py_0
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.2=py_1
  - notebook=5.7.6=py36_0
  - numpy=1.16.2=py36_blas_openblash1522bff_0
  - openblas=0.3.3=h9ac9557_1001
  - openjpeg=2.3.0=hf38bd82_1003
  - openpyxl=2.6.1=py_0
  - openssl=1.1.1b=h14c3975_1
  - orderedset=2.0=py36_0
  - osmnx=0.9=py_1
  - pandas=0.24.2=py36hf484d3e_0
  - pandoc=2.7.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.4=py_0
  - patsy=0.5.1=py_0
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=19.0.3=py36_0
  - pixman=0.34.0=h14c3975_1003
  - pluggy=0.9.0=py_0
  - poppler=0.67.0=h2fc8fa2_1002
  - poppler-data=0.4.9=1
  - postgresql=11.2=h61314c7_0
  - proj4=5.2.0=h14c3975_1001
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_1000
  - py=1.8.0=py_0
  - py-xgboost=0.82=py36he1b5a44_0
  - pycparser=2.19=py36_1
  - pygments=2.3.1=py_0
  - pylint=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.3.1=py_0
  - pyproj=1.9.6=py36hc0953d3_1000
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pyrsistent=0.14.11=py36h14c3975_0
  - pysocks=1.6.8=py36_1002
  - pytest=4.3.1=py36_0
  - pytest-cov=2.6.1=py_0
  - python=3.6.7=h381d211_1004
  - python-dateutil=2.8.0=py_0
  - pytz=2018.9=py_0
  - pyyaml=5.1=py36h14c3975_0
  - pyzmq=18.0.1=py36h0e1adb2_0
  - qtconsole=4.4.3=py_0
  - ratelim=0.1.6=py36_0
  - readline=7.0=hf8c457e_1001
  - requests=2.21.0=py36_1000
  - rtree=0.8.3=py36h666c49c_1002
  - ruamel=1.0=py36_0
  - ruamel.yaml=0.15.89=py36h14c3975_1
  - scikit-learn=0.20.3=py36_blas_openblashebff5e3_0
  - scipy=1.2.1=py36_blas_openblash1522bff_0
  - seaborn=0.9.0=py_0
  - send2trash=1.5.0=py_0
  - setuptools=40.8.0=py36_0
  - shapely=1.6.4=py36h2afed24_1003
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h67949de_1001
  - statsmodels=0.9.0=py36h3010b51_1000
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py_1001
  - tk=8.6.9=h84994c4_1000
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - typed-ast=1.3.1=py36h14c3975_0
  - tzcode=2018g=h14c3975_1001
  - tzlocal=1.5.1=py_0
  - urllib3=1.24.1=py36_1000
  - vincent=0.4.4=py_1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - wrapt=1.11.1=py36h14c3975_0
  - xerces-c=3.2.2=hac72e42_1001
  - xgboost=0.82=py36he1b5a44_0
  - xlrd=1.2.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004
  - dbus=1.13.2=h714fa37_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - pcre=8.43=he6710b0_0
  - qt=5.6.3=h8bf5577_3
  - pip:
    - flake8==3.5.0
    - pycodestyle==2.3.1


