name: crash-model
channels:
- conda-forge
- defaults
dependencies:
- codecov
- fiona
- folium
- gdal=2.2.4
- geopandas
- geocoder
- geojson
- ipdb
- ipython
- jupyter
- matplotlib
- numpy
- openpyxl
- osmnx
# Weird conda packaging bug, will want to revisit version of pandas later
- pandas=0.22
- pyproj
- pytest
- python=3.6
- pyyaml
- pytest-cov
- rtree
- seaborn
- scikit-learn
- shapely
- xgboost
- xlrd