name: boston-crash-model
channels:
- conda-forge
- defaults
dependencies:
- backports.shutil_get_terminal_size
- branca
- ca-certificates
- certifi
- descartes
- entrypoints
- enum34
- expat
- fiona
- folium
- freetype
- freexl
- functools32
- gdal
- geopandas
- geos
- hdf4
- hdf5
- html5lib
- icu
- ipython
- kealib
- krb5
- libiconv
- libnetcdf
- libpng
- libpq
- libspatialindex
- libspatialite
- libtiff
- libxml2
- matplotlib
- nbconvert
- openjpeg
- pandoc
- pcre
- proj4
- pyqt
- pyzmq
- qt
- rtree
- scandir
- setuptools
- shapely
- sip
- six
- ssl_match_hostname
- webencodings
- xerces-c
- alabaster
- astroid
- babel
- backports
- backports_abc
- bleach
- chardet
- click
- click-plugins
- cligj
- colorama
- configparser
- curl
- cycler
- decorator
- docutils
- et_xmlfile
- imagesize
- ipykernel
- ipython_genutils
- ipywidgets
- isort
- jdcal
- jedi
- jinja2
- jpeg
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- lazy-object-proxy
- markupsafe
- mistune
- mkl
- munch
- nbformat
- notebook
- numpy
- numpydoc
- openpyxl
- openssl
- osmnx
- pandas
- pandocfilters
- path.py
- pathlib2
- patsy
- pickleshare
- pip
- prompt_toolkit
- psutil
- psycopg2
- pycodestyle
- pyflakes
- pygments
- pylint
- pyparsing
- pyproj
- pysal
- pytest
- python
- python-dateutil
- pytz
- qtawesome
- qtconsole
- qtpy
- requests
- rope
- scikit-learn
- scipy
- seaborn
- simplegeneric
- singledispatch
- snowballstemmer
- sphinx
- sphinxcontrib
- sphinxcontrib-websupport
- sqlalchemy
- sqlite
- statsmodels
- testpath
- tornado
- traitlets
- typing
- unicodecsv
- vincent
- wcwidth
- wheel
- widgetsnbextension
- wrapt
- pyyaml
- xlrd
- zlib
- xgboost
- pip:
  - backports-abc
  - backports.shutil-get-terminal-size
  - backports.ssl-match-hostname
  - et-xmlfile
  - geocoder
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - prompt-toolkit
  - ratelim
