name: crash-model
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - appnope=0.1.0=py36h9f0ad1d_1001
  - astroid=2.4.2=py36h9f0ad1d_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - boost-cpp=1.72.0=hdf9ef73_0
  - branca=0.4.1=py_0
  - brotlipy=0.7.0=py36h37b9a7d_1000
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hec6a9b0_1003
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.14.0=py36h356ff06_0
  - cfitsio=3.470=h84d2f63_2
  - chardet=3.0.4=py36h9f0ad1d_1006
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - codecov=2.1.7=pyh9f0ad1d_0
  - coverage=5.1=py36h37b9a7d_0
  - cryptography=2.9.2=py36hc9d8292_0
  - curl=7.68.0=h8754def_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py36h9f0ad1d_1001
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.9=h4a8c4bd_2
  - fiona=1.8.9.post2=py36h238e834_0
  - flask=1.1.2=pyh9f0ad1d_0
  - folium=0.11.0=py_0
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.10.2=h8da9a1a_0
  - freexl=1.0.5=h1de35cc_1002
  - future=0.18.2=py36h9f0ad1d_1
  - gdal=2.4.3=py36h1304821_8
  - geocoder=1.38.1=py_1
  - geographiclib=1.50=py_0
  - geojson=2.4.1=py_0
  - geopandas=0.5.1=py_0
  - geopy=1.22.0=pyh9f0ad1d_0
  - geos=3.7.2=h6de7cb9_2
  - geotiff=1.5.1=h2bcb450_3
  - gettext=0.19.8.1=h46ab8bc_1002
  - giflib=5.1.7=h01d97ff_1
  - glib=2.64.3=h577aef8_0
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.5=nompi_h3e39495_1104
  - icu=64.2=h6de7cb9_1
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py36h9f0ad1d_0
  - importlib_metadata=1.6.1=0
  - ipdb=0.13.0=pyh9f0ad1d_0
  - ipykernel=5.3.0=py36h95af2a2_0
  - ipython=7.15.0=py36h9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36h9f0ad1d_1
  - itsdangerous=1.1.0=py_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.1=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9d=h0b31af3_0
  - json-c=0.13.1=h575e443_1002
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - kealib=1.4.13=h2324030_0
  - kiwisolver=1.2.0=py36h863e41a_0
  - krb5=1.16.4=h1752a42_0
  - lazy-object-proxy=1.4.3=py36h37b9a7d_2
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcurl=7.68.0=h709d2b2_0
  - libcxx=10.0.0=h1af66ff_2
  - libdap4=3.20.4=habf5908_0
  - libedit=3.1.20191231=hed1e85f_0
  - libffi=3.2.1=h4a8c4bd_1007
  - libgdal=2.4.3=h48e9a63_8
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - libkml=1.3.0=h169b8f9_1011
  - liblapack=3.8.0=16_openblas
  - libnetcdf=4.7.1=nompi_hec86efb_102
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libpq=11.5=h31a01ba_2
  - libsodium=1.0.17=h01d97ff_0
  - libspatialindex=1.9.3=h4a8c4bd_3
  - libspatialite=4.3.0a=hd0a3780_1030
  - libssh2=1.9.0=h39bdce6_2
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - libxgboost=1.0.2=h4a8c4bd_1
  - libxml2=2.9.10=h53d96d6_0
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h4a8c4bd_1
  - markupsafe=1.1.1=py36h37b9a7d_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py36h83d3ec1_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py36h37b9a7d_1001
  - more-itertools=8.4.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=h0a44026_1002
  - networkx=2.4=py_1
  - notebook=6.0.3=py36h9f0ad1d_0
  - numpy=1.18.5=py36hdc5ca10_0
  - openjpeg=2.3.1=h254dc36_3
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1g=h0b31af3_0
  - osmnx=0.11.4=py_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py36hcc1bba6_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pip=20.1.1=py_1
  - pixman=0.38.0=h01d97ff_1003
  - pluggy=0.13.1=py36h9f0ad1d_2
  - poppler=0.67.0=h16886b5_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h26bc10f_2
  - proj4=6.1.1=hca663eb_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - prompt_toolkit=3.0.5=1
  - ptyprocess=0.6.0=py_1001
  - py=1.8.2=pyh9f0ad1d_0
  - py-xgboost=1.0.2=py36h9f0ad1d_1
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pylint=2.5.3=py36h9f0ad1d_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.2.1=py36h9bb365a_1
  - pyqt=5.9.2=py36h2a560b1_4
  - pyrsistent=0.16.0=py36h37b9a7d_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - pytest=5.4.3=py36h9f0ad1d_0
  - pytest-cov=2.10.0=pyh9f0ad1d_0
  - python=3.6.10=h4334963_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h37b9a7d_0
  - pyzmq=19.0.1=py36h820b253_0
  - qt=5.9.7=h8cf7e54_3
  - qtconsole=4.7.5=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - ratelim=0.1.6=py_2
  - readline=8.0=hcfe32e1_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rtree=0.9.4=py36he053a7a_1
  - ruamel.yaml=0.16.6=py36h37b9a7d_1
  - ruamel.yaml.clib=0.2.0=py36h37b9a7d_1
  - scikit-learn=0.23.1=py36hef903b7_0
  - scipy=1.4.1=py36h1dac7e4_3
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=47.3.1=py36h9f0ad1d_0
  - shapely=1.6.4.post2
  - sip=4.19.8=py36h0a44026_1000
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.30.1=h93121df_0
  - statsmodels=0.11.1=py36h37b9a7d_2
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbbe82c9_0
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py36h37b9a7d_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typed-ast=1.4.1=py36h0b31af3_0
  - tzcode=2020a=h0b31af3_0
  - tzlocal=2.1=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h37b9a7d_0
  - xerces-c=3.2.2=h8f8adb3_1004
  - xlrd=1.2.0=py_0
  - xz=5.2.5=h0b31af3_0
  - yaml=0.2.5=h0b31af3_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.4=h4b3e974_3
prefix: /usr/local/miniconda/envs/crash-model