name: crash-model
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - astroid=2.3.3=py36_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h6a4c333_2
  - branca=0.3.1=py_0
  - bzip2=1.0.8=hfa6e2cd_1
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36hb32ad35_0
  - cfitsio=3.470=hfa6e2cd_2
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - codecov=2.0.15=py_1
  - colorama=0.4.1=py_0
  - coverage=4.5.4=py36hfa6e2cd_0
  - cryptography=2.8=py36hb32ad35_1
  - curl=7.65.3=h4496350_0
  - cycler=0.10.0=py_2
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py36_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.5=he025d50_1004
  - fiona=1.8.12=py36hb7fdc2d_0
  - flask=1.1.1=py_1
  - folium=0.10.1=py_0
  - freetype=2.10.0=h563cfd7_1
  - freexl=1.0.5=hd288d7e_1002
  - future=0.18.2=py36_0
  - gdal=3.0.2=py36h2fee047_5
  - geocoder=1.38.1=py_1
  - geographiclib=1.50=py_0
  - geojson=2.5.0=py_0
  - geopandas=0.6.2=py_0
  - geopy=1.20.0=py_0
  - geos=3.8.0=he025d50_0
  - geotiff=1.5.1=h765a46f_7
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.58.3=py36hc0c2ac7_1002
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.5=nompi_ha405e13_1104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.8=py36_1000
  - importlib_metadata=1.2.0=py36_0
  - intel-openmp=2019.4=245
  - ipdb=0.12.3=py_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipython=7.10.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.2.1=py36_1
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=5.1.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - kealib=1.4.10=hf7dc31f_1005
  - kiwisolver=1.1.0=py36he980bc4_0
  - krb5=1.16.3=hdd46e55_1001
  - lazy-object-proxy=1.4.3=py36hfa6e2cd_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.0=default_hf44288c_4
  - libcurl=7.65.3=h4496350_0
  - libffi=3.2.1=h6538335_1006
  - libgdal=3.0.2=hafedd80_5
  - libiconv=1.15=hfa6e2cd_1005
  - libkml=1.3.0=h4ece8bf_1010
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.7.1=nompi_he2c6080_102
  - libpng=1.6.37=h7602738_0
  - libpq=11.5=hb0bdaea_2
  - libsodium=1.0.17=h2fa13f4_0
  - libspatialindex=1.9.3=he025d50_1
  - libspatialite=4.3.0a=he9c6e69_1033
  - libssh2=1.8.2=h642c060_2
  - libtiff=4.1.0=h21b02b4_1
  - libwebp=1.0.2=hfa6e2cd_4
  - libxgboost=0.90=1
  - libxml2=2.9.10=h9ce36c8_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markupsafe=1.1.1=py36hfa6e2cd_0
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h2981e6d_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py36hfa6e2cd_1000
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - more-itertools=8.0.0=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py_1
  - networkx=2.4=py_0
  - notebook=6.0.1=py36_0
  - numpy=1.17.3=py36hc71023c_0
  - openjpeg=2.3.1=h57dd2e7_3
  - openpyxl=3.0.1=py_0
  - openssl=1.1.1d=hfa6e2cd_0
  - osmnx=0.11=py_0
  - packaging=19.2=py_0
  - pandas=0.25.3=py36he350917_0
  - pandoc=2.8.0.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=h6538335_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.3.1=py36_0
  - pluggy=0.12.0=py_0
  - poppler=0.67.0=h1707e21_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=h06f7779_2
  - proj=6.2.1=ha7a8c7b_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - py=1.8.0=py_0
  - py-xgboost=0.90=py36_1
  - pycparser=2.19=py36_1
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py36_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyproj=2.4.2.post1=py36h9716dcf_0
  - pyqt=5.12.3=py36h6538335_1
  - pyrsistent=0.15.6=py36hfa6e2cd_0
  - pysocks=1.7.1=py36_0
  - pytest=5.0.1=py36_0
  - pytest-cov=2.8.1=py_0
  - python=3.6.7=he025d50_1005
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=225=py36hfa6e2cd_0
  - pywinpty=0.5.7=py36_0
  - pyyaml=5.2=py36hfa6e2cd_0
  - pyzmq=18.1.1=py36h16f9016_0
  - qt=5.12.5=h7ef1ec2_0
  - qtconsole=4.6.0=py_0
  - ratelim=0.1.6=py_2
  - requests=2.22.0=py36_1
  - rtree=0.9.1=py36hbf79ddb_0
  - ruamel.yaml=0.16.5=py36hfa6e2cd_1
  - ruamel.yaml.clib=0.2.0=py36hfa6e2cd_0
  - scikit-learn=0.22=py36h7208079_0
  - scipy=1.3.1=py36h29ff71c_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py36_0
  - shapely=1.6.4=py36h2130f3d_1007
  - six=1.13.0=py36_0
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.10.2=py36hc8d92b1_0
  - tbb=2018.0.5=he980bc4_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tiledb=1.7.0=hffbbd95_2
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.3=py36hfa6e2cd_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36hfa6e2cd_0
  - tzlocal=2.0.0=py_0
  - urllib3=1.25.7=py36_0
  - vc=14.1=h0510ff6_4
  - vincent=0.4.4=py_1
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36_1003
  - winpty=0.4.3=4
  - wrapt=1.11.2=py36hfa6e2cd_0
  - xerces-c=3.2.2=h6538335_1004
  - xlrd=1.2.0=py_0
  - xz=5.2.4=h2fa13f4_1001
  - yaml=0.2.2=hfa6e2cd_1
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.4=hd8a0e53_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1