name: crash-model
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- altair=2.1.0=py_0
- asn1crypto=0.24.0=py36_0
- atomicwrites=1.1.5=py36_0
- attrs=18.1.0=py_1
- backcall=0.1.0=py_0
- bleach=2.1.3=py_0
- boost=1.66.0=py36_vc14_1
- boost-cpp=1.66.0=vc14_1
- branca=0.3.0=py_0
- ca-certificates=2018.4.16=0
- certifi=2018.4.16=py36_0
- cffi=1.11.5=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py_1
- click-plugins=1.0.3=py36_0
- cligj=0.4.0=py36_0
- colorama=0.3.9=py36_0
- cryptography=2.2.1=py36_0
- curl=7.60.0=vc14_0
- cycler=0.10.0=py36_0
- decorator=4.3.0=py_0
- descartes=1.1.0=py_1
- entrypoints=0.2.3=py36_1
- et_xmlfile=1.0.1=py36_0
- expat=2.2.5=vc14_0
- fiona=1.7.12=py36_0
- folium=0.5.0=py_0
- freetype=2.8.1=vc14_0
- freexl=1.0.5=vc14_0
- gdal=2.2.4=py36_0
- geocoder=1.38.1=py_0
- geographiclib=1.49=py_0
- geojson=2.3.0=py_0
- geopandas=0.3.0=py36_0
- geopy=1.14.0=py_0
- geos=3.6.2=vc14_1
- geotiff=1.4.2=vc14_1
- hdf4=4.2.13=vc14_0
- hdf5=1.10.1=vc14_2
- html5lib=1.0.1=py_0
- icu=58.2=vc14_0
- idna=2.7=py36_0
- ipdb=0.11=py36_0
- ipykernel=4.8.2=py36_0
- ipython=6.4.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.2.1=py36_1
- jdcal=1.4=py36_0
- jedi=0.12.0=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=vc14_2
- jsonschema=2.6.0=py36_1
- jupyter=1.0.0=py_1
- jupyter_client=5.2.3=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- kealib=1.4.7=vc14_4
- kiwisolver=1.0.1=py36_1
- krb5=1.14.6=vc14_0
- libgdal=2.2.4=vc14_4
- libiconv=1.15=vc14_0
- libnetcdf=4.6.1=vc14_2
- libpng=1.6.34=vc14_0
- libpq=9.6.3=vc14_0
- libsodium=1.0.16=vc14_0
- libspatialindex=1.8.5=vc14_1
- libspatialite=4.3.0a=vc14_19
- libssh2=1.8.0=vc14_2
- libtiff=4.0.9=vc14_0
- libxml2=2.9.8=vc14_0
- markupsafe=1.0=py36_0
- matplotlib=2.2.2=py36_1
- mistune=0.8.3=py36_1
- more-itertools=4.2.0=py_0
- munch=2.3.2=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- networkx=2.1=py36_0
- notebook=5.5.0=py36_0
- openjpeg=2.3.0=vc14_2
- openpyxl=2.5.4=py36_0
- openssl=1.0.2o=vc14_0
- orderedset=2.0.1=py36_0
- osmnx=0.8.1=py_0
- pandas=0.22.0=py36_1
- pandoc=2.2.1=hde52d81_0
- pandocfilters=1.4.2=py36_0
- parso=0.2.1=py_0
- patsy=0.5.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.3=py36_0
- pluggy=0.6.0=py_0
- proj4=4.9.3=vc14_5
- prompt_toolkit=1.0.15=py36_0
- psycopg2=2.7.4=py36_0
- py=1.5.3=py_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=18.0.0=py36_0
- pyparsing=2.2.0=py36_0
- pyproj=1.9.5.1=py36_0
- pyqt=5.6.0=py36_5
- pysal=1.14.3=py36_0
- pysocks=1.6.8=py36_1
- pytest=3.6.1=py36_0
- python=3.6.5=1
- python-dateutil=2.7.3=py_0
- pytz=2018.4=py_0
- pywinpty=0.5.4=py36_0
- pyyaml=3.12=py36_1
- pyzmq=17.0.0=py36_4
- qt=5.6.2=vc14_1
- qtconsole=4.3.1=py36_0
- ratelim=0.1.6=py36_0
- requests=2.19.1=py36_0
- rtree=0.8.3=py36_0
- seaborn=0.8.1=py36_0
- send2trash=1.5.0=py_0
- setuptools=39.2.0=py36_0
- shapely=1.6.4=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlalchemy=1.2.8=py36_0
- sqlite=3.20.1=vc14_2
- statsmodels=0.9.0=py36_0
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- toolz=0.9.0=py_0
- tornado=5.0.2=py36_0
- traitlets=4.3.2=py36_0
- typing=3.6.4=py36_0
- tzlocal=1.5.1=py_0
- urllib3=1.22=py36_0
- vc=14=0
- vincent=0.4.4=py36_0
- vs2015_runtime=14.0.25420=0
- wcwidth=0.1.7=py36_0
- webencodings=0.5.1=py36_0
- wheel=0.31.0=py36_0
- widgetsnbextension=3.2.1=py36_0
- win_inet_pton=1.0.1=py36_1
- wincertstore=0.2=py36_0
- winpty=0.4.3=4
- xerces-c=3.2.0=vc14_0
- xlrd=1.1.0=py_2
- xz=5.2.3=0
- yaml=0.1.7=vc14_0
- zeromq=4.2.5=vc14_1
- zlib=1.2.11=vc14_0
- m2w64-gcc-libgfortran=5.3.0=6
- m2w64-gcc-libs=5.3.0=7
- m2w64-gcc-libs-core=5.3.0=7
- m2w64-gmp=6.1.0=2
- m2w64-libwinpthread-git=5.0.0.4634.697f757=2
- mkl=2017.0.3=0
- msys2-conda-epoch=20160418=1
- numpy=1.13.1=py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - win-inet-pton==1.0.1

