name: crash-model
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _py-xgboost-mutex=2.0=cpu_0
  - astroid=2.3.3=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - boost-cpp=1.70.0=h8e57a91_2
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - cfitsio=3.470=hb60a0a2_2
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - codecov=2.0.15=py_1
  - coverage=4.5.4=py36h516909a_0
  - cryptography=2.8=py36h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py36_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.5=he1b5a44_1004
  - fiona=1.8.12=py36h900e953_0
  - flask=1.1.1=py_1
  - folium=0.10.1=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - future=0.18.2=py36_0
  - gdal=3.0.2=py36hbb6b9fb_4
  - geocoder=1.38.1=py_1
  - geographiclib=1.50=py_0
  - geojson=2.4.1=py_0
  - geopandas=0.5.1=py_0
  - geopy=1.20.0=py_0
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=hbd99317_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=py36h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - importlib_metadata=1.2.0=py36_0
  - ipdb=0.12.3=py_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipython=7.10.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.2.1=py36_1
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=5.1.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - kealib=1.4.10=h58c409b_1005
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - lazy-object-proxy=1.4.3=py36h516909a_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.0=default_hde54327_4
  - libcurl=7.65.3=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgdal=3.0.2=h852c1c0_4
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.0=hc9558a2_3
  - libnetcdf=4.7.1=nompi_h94020b1_102
  - libopenblas=0.3.7=h5ec1e0e_4
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_2
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_1
  - libspatialite=4.3.0a=h4f6d029_1032
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_1
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=hf4e8a37_4
  - libxcb=1.13=h14c3975_1002
  - libxgboost=0.90=he1b5a44_4
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py36h516909a_0
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h250f245_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py36h516909a_1000
  - more-itertools=8.0.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_0
  - notebook=6.0.1=py36_0
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.17.3=py36h95a1406_0
  - openjpeg=2.3.1=h981e76c_3
  - openpyxl=3.0.1=py_0
  - openssl=1.1.1d=h516909a_0
  - osmnx=0.11=py_0
  - packaging=19.2=py_0
  - pandas=0.25.3=py36hb3f55d8_0
  - pandoc=2.8.0.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.12.0=py_0
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_2
  - proj=6.2.1=hc80f0dc_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - py-xgboost=0.90=py36_4
  - pycparser=2.19=py36_1
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py36_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.5=py_0
  - pyproj=2.4.2.post1=py36h12732c1_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pyrsistent=0.15.6=py36h516909a_0
  - pysocks=1.7.1=py36_0
  - pytest=5.3.1=py36_0
  - pytest-cov=2.8.1=py_0
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py36h516909a_0
  - pyzmq=18.1.1=py36h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.6.0=py_0
  - ratelim=0.1.6=py_2
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - rtree=0.9.1=py36h7b0cdae_0
  - ruamel.yaml=0.16.5=py36h516909a_1
  - ruamel.yaml.clib=0.2.0=py36h516909a_0
  - scikit-learn=0.22=py36hcdab131_0
  - scipy=1.3.2=py36h921218d_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py_0
  - setuptools=42.0.2=py36_0
  - shapely=1.6.4=py36hec07ddf_1006
  - six=1.13.0=py36_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.10.2=py36hc1659b7_0
  - tbb=2018.0.5=h2d50403_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tiledb=1.7.0=hcde45ca_2
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py36h516909a_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36h516909a_0
  - tzcode=2019a=h516909a_1002
  - tzlocal=2.0.0=py_0
  - urllib3=1.25.7=py36_0
  - vincent=0.4.4=py_1
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - wrapt=1.11.2=py36h516909a_0
  - xerces-c=3.2.2=h8412b87_1004
  - xlrd=1.2.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1


