# City name
city: Los Angeles, CA, USA
# City centerpoint latitude & longitude (default geocoded values set)
city_latitude: 34.0522
city_longitude: -118.2437

# City's time zone: defaults to the local time zone of computer initializing the city's config file
timezone: America/Los_Angeles
# Radius of city's road network from centerpoint in km, required if OSM has no polygon data (defaults to 20km)
city_radius: 50

# The folder under data where this city's data is stored
name: losangeles

# If given, limit crashes to after startdate and no later than enddate
# Recommended to limit to just a few years for now
startdate: 1/1/2016
enddate: 

#################################################################
# Configuration for data standardization

# crash file configurations
crashes_files:
  LA_TrafficData.csv:
    required:
      id: ID
      latitude: Latitude 
      longitude: Longitude
      # If date supplied in single column:
      date_complete: Date
      # If date is separated into year/month/day:
      date_year: 
      date_month: 
      # Leave date_day empty if not available
      date_day: 
      # If time is available and separate from date:
      time: Time
      # If time specified, time_format is one of:
      # default (HH:MM:SS)
      # seconds (since midnight)
      # military (HHMM)
      time_format: military
    optional:
      summary: 
      # If the crash file doesn't have a lat/lon, you must give the address field
      # and you will need to run the geocode_batch script - see the README
      address: Address
      vehicles: 
      bikes: 

#################################################################
# Configuration for default features

# Default features from open street map. You can remove features you don't want
# Note: we don't support adding features in the config file.
# If there is an additional feature you want from open street map, contact the development team
openstreetmap_features:
  categorical:
    width: Width
    cycleway_type: Bike lane
    signal: Signal
    oneway: One Way
    lanes: Number of lanes
  continuous:
    width_per_lane: Average width per lane


