# City name
city: Brisbane, Australia
# City centerpoint latitude & longitude (default geocoded values set)
city_latitude: -27.4697707
city_longitude: 153.0251235
timezone: Australia/Brisbane
# Radius of city's road network from centerpoint in km, required if OSM has no polygon data (defaults to 20km)
city_radius: 10
# The folder under data where this city's data is stored
name: brisbane
# If given, limit crashes to after startdate and no later than enddate
# Recommended to limit to just a few years for now
startdate: 2015-01-01
enddate: 2017-12-31
# The type of predictions to generate, 'segment' is default, 'week' is legacy
level: 'segment'

#################################################################
# Configuration for data standardization

# crash file configurations
crashes_files:
  locations_2014_2017.csv:
    required:
      id: Crash_Ref_Number
      latitude: Crash_Latitude_GDA94
      longitude: Crash_Longitude_GDA94
      # If date supplied in single column:
      date_complete: Crash_Date
      # If date is separated into year/month/day:
      date_year: 
      date_month: 
      # Leave date_day empty if not available
      date_day: 
      # If time is available and separate from date:
      time: 
      # If time specified, time_format is one of:
      # default (HH:MM:SS)
      # seconds (since midnight)
      # military (HHMM)
      time_format: 
    optional:
      summary: Crash_DCA_Description
      address: Crash_Street
      vehicles: 
      bikes: 

# If using legacy 'week' predictions:
# specify year & week on which to predict crashes (best practice is year & week towards the end of your crash data set
# in format [month, year]
time_target: [30, 2017]
# specify how many weeks back to predict in output of train_model
weeks_back: 1